-- MySQL Script generated by MySQL Workbench
-- Tue Jul 14 21:23:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema wellness_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wellness_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wellness_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `wellness_db` ;

-- -----------------------------------------------------
-- Table `wellness_db`.`activity_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`activity_category` (
  `category_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัสหมวดหมู่ (PK)',
  `category_name` VARCHAR(100) NOT NULL COMMENT 'ชื่อหมวดหมู่ เช่น วิ่ง, ปั่นจักรยาน, ว่ายน้ำ',
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE=เปิดใช้งาน แสดงในแอปให้เลือก, INACTIVE=ปิดใช้งานชั่วคราว ไม่ลบเพราะมีกิจกรรมย่อยผูกอยู่',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันเวลาที่สร้างหมวดหมู่',
  `updated_at` DATETIME NULL DEFAULT NULL COMMENT 'วันเวลาที่แก้ไขล่าสุด',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'หมวดหมู่กิจกรรมออกกำลังกาย';


-- -----------------------------------------------------
-- Table `wellness_db`.`activity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`activity_type` (
  `activity_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัสประเภทกิจกรรม (PK)',
  `category_id` INT NOT NULL COMMENT 'อ้างอิงหมวดหมู่ที่กิจกรรมนี้สังกัด (FK -> activity_category.category_id)',
  `activity_name` VARCHAR(100) NOT NULL COMMENT 'ชื่อกิจกรรม เช่น \"วิ่ง 5 km\", \"วิ่ง 10 km\"',
  `score` INT NOT NULL DEFAULT '0' COMMENT 'คะแนนมาตรฐานที่พนักงานจะได้รับเมื่อ submission ของกิจกรรมนี้ถูกอนุมัติ',
  `require_image` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1=ต้องแนบรูปหลักฐานตอนส่ง submission, 0=ไม่บังคับ',
  `description` VARCHAR(255) NULL DEFAULT NULL COMMENT 'รายละเอียด/เงื่อนไขเพิ่มเติมของกิจกรรม',
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE=เปิดให้ส่งกิจกรรมนี้ได้, INACTIVE=ปิดรับชั่วคราว (เช่น ปรับคะแนนใหม่)',
  PRIMARY KEY (`activity_id`),
  INDEX `fk_activity_type_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_activity_type_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `wellness_db`.`activity_category` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ประเภทกิจกรรมย่อยและคะแนนมาตรฐานของแต่ละกิจกรรม';


-- -----------------------------------------------------
-- Table `wellness_db`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`employee` (
  `employee_id` VARCHAR(20) NOT NULL COMMENT 'รหัสพนักงาน format เดียวกับระบบ Pulse (PK)',
  `full_name` VARCHAR(150) NOT NULL COMMENT 'ชื่อ-สกุล ใช้แสดงบน leaderboard เมื่อ join_mode = PUBLIC',
  `department` VARCHAR(100) NULL DEFAULT NULL COMMENT 'แผนกที่สังกัด ใช้ทำ filter/report แยกแผนกในอนาคต',
  `employment_status` ENUM('ACTIVE', 'RESIGNED') NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE=ยังทำงานอยู่ (login/ส่งกิจกรรมได้), RESIGNED=ลาออกแล้ว (ต้องบล็อกไม่ให้ login ใหม่)',
  `role` ENUM('EMPLOYEE', 'ADMIN') NOT NULL DEFAULT 'EMPLOYEE',
  `synced_at` DATETIME NULL DEFAULT NULL COMMENT 'วันเวลาที่ sync ข้อมูลจาก Pulse ล่าสุด (debug ว่าข้อมูล stale รึยัง)',
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ตาราง mirror ข้อมูลพนักงานจากระบบ Pulse (HR) — sync แบบ upsert เป็นรอบ ไม่ query ข้าม database';


-- -----------------------------------------------------
-- Table `wellness_db`.`admin_credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`admin_credential` (
  `employee_id` VARCHAR(20) NOT NULL COMMENT 'รหัสพนักงานที่มีสิทธิ์แอดมิน (PK, FK -> employee.employee_id)',
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'รหัสผ่านที่ hash แล้วด้วย bcrypt ห้ามเก็บ plain text เด็ดขาด',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันเวลาที่ตั้งรหัสผ่านนี้',
  PRIMARY KEY (`employee_id`),
  CONSTRAINT `fk_admin_credential_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wellness_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ข้อมูล login สำหรับหน้าแอดมิน แยกจากช่องทาง LINE login ของพนักงานทั่วไป';


-- -----------------------------------------------------
-- Table `wellness_db`.`badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`badge` (
  `badge_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัส Badge (PK)',
  `badge_name` VARCHAR(100) NOT NULL COMMENT 'ชื่อ Badge เช่น \"Runner\", \"Marathon Master\"',
  `description` VARCHAR(255) NULL DEFAULT NULL COMMENT 'คำอธิบาย Badge / เงื่อนไขการได้รับแบบอ่านง่าย',
  `icon` VARCHAR(255) NULL DEFAULT NULL COMMENT 'path/URL รูปไอคอนของ Badge',
  `condition_type` VARCHAR(50) NOT NULL COMMENT 'ประเภทเงื่อนไข เช่น DISTANCE (ระยะทางสะสม), SUBMISSION_COUNT (จำนวนครั้งที่ส่ง), SCORE (คะแนนสะสม)',
  `condition_value` INT NOT NULL COMMENT 'ค่าที่ต้องทำถึงจึงจะได้ Badge เช่น 100 (กม.)',
  PRIMARY KEY (`badge_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'เหรียญตราความสำเร็จที่พนักงานสะสมได้';


-- -----------------------------------------------------
-- Table `wellness_db`.`challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`challenge` (
  `challenge_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัส Challenge (PK)',
  `activity_id` INT NOT NULL COMMENT 'ประเภทกิจกรรมที่ใช้ในการแข่งขันนี้ (FK -> activity_type.activity_id) เช่น นับเฉพาะ \"วิ่ง\"',
  `challenge_name` VARCHAR(150) NOT NULL COMMENT 'ชื่อ Challenge เช่น \"July Run Challenge\"',
  `description` VARCHAR(255) NULL DEFAULT NULL COMMENT 'รายละเอียด/กติกาการแข่งขัน',
  `ranking_type` ENUM('DISTANCE') NOT NULL DEFAULT 'DISTANCE' COMMENT 'เกณฑ์การจัดอันดับ ปัจจุบันมีแบบเดียวคือระยะทางสะสม (DISTANCE)',
  `start_date` DATETIME NOT NULL COMMENT 'วันเวลาเริ่ม Challenge',
  `end_date` DATETIME NOT NULL COMMENT 'วันเวลาสิ้นสุด Challenge',
  `status` ENUM('UPCOMING', 'ONGOING', 'ENDED', 'CANCELLED') NOT NULL DEFAULT 'UPCOMING' COMMENT 'UPCOMING=ยังไม่เริ่ม, ONGOING=กำลังแข่งขัน, ENDED=จบแล้ว, CANCELLED=ถูกยกเลิกโดย admin',
  PRIMARY KEY (`challenge_id`),
  INDEX `fk_challenge_activity_type_idx` (`activity_id` ASC) VISIBLE,
  CONSTRAINT `fk_challenge_activity_type`
    FOREIGN KEY (`activity_id`)
    REFERENCES `wellness_db`.`activity_type` (`activity_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'กิจกรรมแข่งขันแบบมีช่วงเวลาเริ่ม-จบ';


-- -----------------------------------------------------
-- Table `wellness_db`.`challenge_participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`challenge_participant` (
  `participant_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัสผู้เข้าร่วม (PK)',
  `challenge_id` INT NOT NULL COMMENT 'Challenge ที่เข้าร่วม (FK -> challenge.challenge_id)',
  `employee_id` VARCHAR(20) NOT NULL COMMENT 'รหัสพนักงานผู้เข้าร่วม (placeholder รอเชื่อมระบบ Pulse/HR)',
  `join_mode` ENUM('PUBLIC', 'ANONYMOUS') NOT NULL DEFAULT 'PUBLIC' COMMENT 'PUBLIC=แสดงชื่อจริงบน leaderboard, ANONYMOUS=ซ่อนตัวตน (ควรมีฟิลด์ display_alias เพิ่มถ้าจะโชว์ leaderboard แบบไม่ระบุตัวตน)',
  `joined_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันเวลาที่กดเข้าร่วม — ใช้เป็นจุดเริ่มนับคะแนนของ challenge นี้ (submission ก่อนหน้าวันนี้จะไม่ถูกนับ)',
  PRIMARY KEY (`participant_id`),
  UNIQUE INDEX `uq_challenge_employee` (`challenge_id` ASC, `employee_id` ASC) COMMENT '\'กันพนักงาน 1 คนกดเข้าร่วม challenge เดียวกันซ้ำ\'' VISIBLE,
  INDEX `idx_challenge_participant_employee` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_challenge_participant_challenge`
    FOREIGN KEY (`challenge_id`)
    REFERENCES `wellness_db`.`challenge` (`challenge_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_challenge_participant_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wellness_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'รายชื่อพนักงานที่เข้าร่วมแต่ละ Challenge';


-- -----------------------------------------------------
-- Table `wellness_db`.`reject_reason`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`reject_reason` (
  `reason_id` INT NOT NULL AUTO_INCREMENT,
  `reason_text` VARCHAR(255) NOT NULL,
  `is_other` TINYINT(1) NOT NULL DEFAULT '0',
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`reason_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'preset เหตุผลการปฏิเสธ submission ให้แอดมินเลือกจาก dropdown';


-- -----------------------------------------------------
-- Table `wellness_db`.`running_submission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`running_submission` (
  `submission_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัสการส่ง (PK)',
  `employee_id` VARCHAR(20) NOT NULL COMMENT 'รหัสพนักงานผู้ส่งกิจกรรม',
  `activity_id` INT NOT NULL COMMENT 'ประเภทกิจกรรมที่ส่ง',
  `distance` DECIMAL(5,2) NULL DEFAULT NULL COMMENT 'ระยะทาง (กม.) — ใช้คำนวณ ranking ใน challenge แบบ DISTANCE',
  `duration` INT NULL DEFAULT NULL COMMENT 'ระยะเวลาที่ใช้ (นาที)',
  `proof_image` VARCHAR(255) NULL DEFAULT NULL COMMENT 'path/URL รูปหลักฐาน (บังคับถ้า activity_type.require_image = 1)',
  `note` VARCHAR(255) NULL DEFAULT NULL COMMENT 'หมายเหตุที่พนักงานพิมพ์แนบมา',
  `reject_reason_id` INT NULL DEFAULT NULL,
  `reject_reason_note` VARCHAR(255) NULL DEFAULT NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING=รอตรวจสอบ, APPROVED=อนุมัติแล้ว (จะไป trigger score_transaction ประเภท EARN), REJECTED=ถูกปฏิเสธ ไม่ได้คะแนน',
  `approved_by` VARCHAR(20) NULL DEFAULT NULL COMMENT 'รหัส admin ผู้ตรวจสอบ/อนุมัติ',
  `approved_at` DATETIME NULL DEFAULT NULL COMMENT 'วันเวลาที่อนุมัติ/ปฏิเสธ',
  `submitted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันเวลาที่พนักงานส่งกิจกรรม',
  PRIMARY KEY (`submission_id`),
  INDEX `fk_running_submission_activity_type_idx` (`activity_id` ASC) VISIBLE,
  INDEX `idx_running_submission_employee` (`employee_id` ASC) VISIBLE,
  INDEX `fk_running_submission_reject_reason` (`reject_reason_id` ASC) VISIBLE,
  CONSTRAINT `fk_running_submission_activity_type`
    FOREIGN KEY (`activity_id`)
    REFERENCES `wellness_db`.`activity_type` (`activity_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_running_submission_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wellness_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_running_submission_reject_reason`
    FOREIGN KEY (`reject_reason_id`)
    REFERENCES `wellness_db`.`reject_reason` (`reason_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ประวัติการส่งผลกิจกรรมของพนักงานแต่ละครั้ง';


-- -----------------------------------------------------
-- Table `wellness_db`.`challenge_submission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`challenge_submission` (
  `challenge_submission_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัส (PK)',
  `participant_id` INT NOT NULL COMMENT 'ผู้เข้าร่วมที่เจ้าของ submission นี้ (FK -> challenge_participant.participant_id)',
  `submission_id` INT NOT NULL COMMENT 'submission ที่ถูกนำมานับ (FK -> running_submission.submission_id)',
  `added_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันเวลาที่ submission นี้ถูกนำเข้ามานับใน challenge',
  PRIMARY KEY (`challenge_submission_id`),
  UNIQUE INDEX `uq_challenge_submission` (`submission_id` ASC) COMMENT '\'กัน submission เดียวกันถูกนับซ้ำเข้า challenge มากกว่า 1 ครั้ง\'' VISIBLE,
  INDEX `fk_challenge_submission_participant_idx` (`participant_id` ASC) VISIBLE,
  CONSTRAINT `fk_challenge_submission_participant`
    FOREIGN KEY (`participant_id`)
    REFERENCES `wellness_db`.`challenge_participant` (`participant_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_challenge_submission_running_submission`
    FOREIGN KEY (`submission_id`)
    REFERENCES `wellness_db`.`running_submission` (`submission_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'เชื่อม submission ที่ผ่านการอนุมัติเข้ากับ challenge ที่พนักงานเข้าร่วมอยู่';


-- -----------------------------------------------------
-- Table `wellness_db`.`employee_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`employee_account` (
  `account_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัสบัญชี (PK)',
  `employee_id` VARCHAR(20) NOT NULL COMMENT 'รหัสพนักงาน (placeholder รอเชื่อมระบบ Pulse/HR)',
  `provider` ENUM('LINE') NOT NULL DEFAULT 'LINE' COMMENT 'ผู้ให้บริการ login ปัจจุบันมีแค่ LINE',
  `provider_user_id` VARCHAR(255) NOT NULL COMMENT 'LINE User ID (userId ที่ได้จาก LINE Login/Messaging API)',
  `display_name` VARCHAR(100) NULL DEFAULT NULL COMMENT 'ชื่อที่แสดงจาก LINE profile',
  `picture_url` VARCHAR(255) NULL DEFAULT NULL COMMENT 'URL รูปโปรไฟล์จาก LINE',
  `linked_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันเวลาที่เชื่อมบัญชีครั้งแรก',
  `last_login` DATETIME NULL DEFAULT NULL COMMENT 'วันเวลาเข้าใช้งานล่าสุด',
  `status` ENUM('ACTIVE', 'INACTIVE', 'REVOKED') NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE=ใช้งานได้ปกติ, INACTIVE=ไม่ได้ใช้งาน/ยังไม่ยืนยัน, REVOKED=ถูกตัดสิทธิ์ (เช่น พนักงานลาออก)',
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `uq_provider_user` (`provider` ASC, `provider_user_id` ASC) COMMENT '\'กัน LINE user คนเดียวกัน login แล้วสร้างบัญชีซ้ำ\'' VISIBLE,
  INDEX `idx_employee_account_employee` (`employee_id` ASC) VISIBLE,
  INDEX `fk_employee_account_employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_account_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wellness_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'การเชื่อมบัญชีพนักงานกับ LINE OA';


-- -----------------------------------------------------
-- Table `wellness_db`.`employee_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`employee_badge` (
  `employee_badge_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัส (PK)',
  `employee_id` VARCHAR(20) NOT NULL COMMENT 'รหัสพนักงานผู้ได้รับ Badge',
  `badge_id` INT NOT NULL COMMENT 'Badge ที่ได้รับ (FK -> badge.badge_id)',
  `received_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันเวลาที่ได้รับ Badge (ระบบคำนวณเงื่อนไขผ่านแล้ว)',
  PRIMARY KEY (`employee_badge_id`),
  UNIQUE INDEX `uq_employee_badge` (`employee_id` ASC, `badge_id` ASC) COMMENT '\'กันพนักงานได้ Badge เดิมซ้ำสองครั้ง\'' VISIBLE,
  INDEX `fk_employee_badge_badge_idx` (`badge_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_badge_badge`
    FOREIGN KEY (`badge_id`)
    REFERENCES `wellness_db`.`badge` (`badge_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_badge_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wellness_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'บันทึก Badge ที่พนักงานแต่ละคนสะสมได้แล้ว';


-- -----------------------------------------------------
-- Table `wellness_db`.`reward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`reward` (
  `reward_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัสของรางวัล (PK)',
  `reward_name` VARCHAR(150) NOT NULL COMMENT 'ชื่อของรางวัล เช่น \"กระบอกน้ำ\"',
  `required_score` INT NOT NULL COMMENT 'คะแนนที่ต้องใช้แลก 1 ชิ้น',
  `stock` INT NOT NULL DEFAULT '0' COMMENT 'จำนวนคงเหลือ — ถูกหักทันทีตอน reward_redeem.status = PENDING (จองของ) และคืนกลับถ้า CANCELLED/REJECTED ภายหลัง เพื่อป้องกัน race condition ตอนของเหลือน้อย',
  `image` VARCHAR(255) NULL DEFAULT NULL COMMENT 'path/URL รูปของรางวัล',
  `description` VARCHAR(255) NULL DEFAULT NULL COMMENT 'รายละเอียดของรางวัล',
  `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE=เปิดให้แลกได้, INACTIVE=ปิดรับแลกชั่วคราว (ไม่ลบเพราะมีประวัติการแลกเก่าผูกอยู่)',
  PRIMARY KEY (`reward_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ของรางวัลที่แลกได้ด้วยคะแนนสะสม';


-- -----------------------------------------------------
-- Table `wellness_db`.`reward_redeem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`reward_redeem` (
  `redeem_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัสการแลก (PK)',
  `employee_id` VARCHAR(20) NOT NULL COMMENT 'รหัสพนักงานผู้แลก',
  `reward_id` INT NOT NULL COMMENT 'ของรางวัลที่แลก (FK -> reward.reward_id)',
  `used_score` INT NOT NULL COMMENT 'คะแนนที่ถูกหักไปสำหรับการแลกครั้งนี้ (เก็บค่า ณ ตอนแลก เผื่อ required_score ของ reward เปลี่ยนภายหลัง)',
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING=รอดำเนินการ (หัก stock+คะแนนไปแล้ว), APPROVED=อนุมัติ/มอบของแล้ว, REJECTED=แอดมินปฏิเสธ (ต้องคืน stock+คะแนนเสมอ), CANCELLED=พนักงาน/ระบบยกเลิกเอง (ต้องคืน stock+คะแนนเสมอ)',
  `redeem_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันเวลาที่กดแลก',
  PRIMARY KEY (`redeem_id`),
  INDEX `fk_reward_redeem_reward_idx` (`reward_id` ASC) VISIBLE,
  INDEX `idx_reward_redeem_employee` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_reward_redeem_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wellness_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reward_redeem_reward`
    FOREIGN KEY (`reward_id`)
    REFERENCES `wellness_db`.`reward` (`reward_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'ประวัติการแลกของรางวัลของพนักงาน';


-- -----------------------------------------------------
-- Table `wellness_db`.`score_transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wellness_db`.`score_transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT COMMENT 'รหัสรายการ (PK)',
  `submission_id` INT NULL DEFAULT NULL COMMENT 'อ้างอิง submission ที่ทำให้เกิดรายการนี้ (FK -> running_submission.submission_id) ใช้เมื่อ transaction_type = EARN',
  `redeem_id` INT NULL DEFAULT NULL COMMENT 'อ้างอิงการแลกของที่ทำให้เกิดรายการนี้ (FK -> reward_redeem.redeem_id) ใช้เมื่อ transaction_type = REDEEM หรือ ADJUST (คืนคะแนนตอน REJECTED/CANCELLED)',
  `employee_id` VARCHAR(20) NOT NULL COMMENT 'รหัสพนักงานเจ้าของรายการ',
  `score` INT NOT NULL COMMENT 'จำนวนคะแนน เป็นบวก=ได้คะแนนเพิ่ม, เป็นลบ=ถูกหักคะแนน (คะแนนคงเหลือของพนักงาน = SUM(score) ของทุกแถว)',
  `transaction_type` ENUM('EARN', 'REDEEM', 'ADJUST', 'EXPIRE') NOT NULL COMMENT 'EARN=ได้คะแนนจาก submission ที่อนุมัติ, REDEEM=ถูกหักตอนแลกของ (PENDING), ADJUST=ปรับคะแนนคืน/แก้ไขโดย admin (เช่น คืนคะแนนตอน redeem ถูก REJECTED), EXPIRE=คะแนนหมดอายุ',
  `remark` VARCHAR(255) NULL DEFAULT NULL COMMENT 'หมายเหตุ/เหตุผลของรายการ เช่น \"คืนคะแนนจากการยกเลิกแลกของ\"',
  `created_by` VARCHAR(20) NULL DEFAULT NULL COMMENT 'ผู้สร้างรายการ (NULL=ระบบสร้างอัตโนมัติ, มีค่า=admin เป็นคนทำรายการ)',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'วันเวลาที่เกิดรายการ',
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_score_transaction_running_submission_idx` (`submission_id` ASC) VISIBLE,
  INDEX `fk_score_transaction_reward_redeem_idx` (`redeem_id` ASC) VISIBLE,
  INDEX `idx_score_transaction_employee` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_score_transaction_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `wellness_db`.`employee` (`employee_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_score_transaction_reward_redeem`
    FOREIGN KEY (`redeem_id`)
    REFERENCES `wellness_db`.`reward_redeem` (`redeem_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_score_transaction_running_submission`
    FOREIGN KEY (`submission_id`)
    REFERENCES `wellness_db`.`running_submission` (`submission_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Ledger บันทึกทุกรายการที่กระทบคะแนนพนักงาน ห้ามแก้ไข/ลบย้อนหลัง ให้ insert รายการปรับเข้าไปแทนเสมอ';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
